### ISSUE TITLE
Extract Text from OCR annotated PDFs.

### ISSUE THREAD

**Issue by l00mi** [zazuko/amos#15]
16h

- [x] Nicolas provides an example
- [x] Quentin analyses provides an example

**Comment by PlekszyGladz** [comment]
3 main specs for OCR in PDFs (the genereal Idea is mentioned here: https://github.com/zazuko/amos/issues/1#issuecomment-762925741):
- Inside the IIIF-Viewer: Fulltext search for a whole document (document = images in one IIIF-Manifest)
- Inside the IIIF-Viewer: Mark text by click and drag and copy-paste it
- Searching fulltexts of all available documents in RDF.

At the moment the first and second are must-haves, while the last is nice to have.

**Comment by sandhose** [comment]
I've worked on it quite a bit, this is what I found so far.

- the best bet to parse PDFs in a JS environment seems to be [PDF.js](https://www.npmjs.com/package/pdfjs-dist) by Mozilla
- extracting words seems fine, extracting lines and paragraphs seems a lot harder
- the quality of the OCR data in provided PDFs is kinda inconsistent
- parsing ~1150 pages takes about a minute on my host, seems to be CPU bound, since one core is spinning 100% on my host when doing this
- seems like the "IIIF way" to do it is to annotate using Web Annotation and their ["Text Granularity Extension"](https://iiif.io/api/extension/text-granularity/), which allows to annotate the document with page/block/line/word/glyph level annotation.
- Mirador operates on a Line level, while the data we extract from PDFs are Word level
- IIIF specs kinda changed in v2.0 -> v3.0. For example, their [JSON-LD context](https://iiif.io/api/presentation/3/context.json) has `{"id": "@id", "type": "@type"}`, which makes some documents/libraries use `id`/`type` instead of `@id`/`@type`. I upgraded Cantaloupe to v5 (which came out 4 days ago) because it supports IIIF Image API 3.0

**Comment by l00mi** [comment]
## examples
### OCR Phonebook Example (Abby Software) -> looks good

### OCR From Scanner (OmniScan Software) ->  difficult as letters are saved, not words 
<img width="1032" alt="Screenshot 2021-03-30 at 13 38 00" src="https://user-images.githubusercontent.com/502518/112982807-36a98f00-915d-11eb-9c3d-52a6b2810264.png">

## used hours
* 10h until now used
* takes ~5h more ?

**Comment by l00mi** [comment]
The exported data will only used inside the IIIF manifest for now, and is not searchable or accessible through the triple store.

**Comment by l00mi** [comment]
@sandhose Injected the OCR annotations as WebAnnotations in the Manifest. This allows the overlay in the Mirador Viewer.

For search we need a separate Search API Server. The Manifest would need to have the information where the Search API Server is.

Only client side search in viewers seem not to be available, for bigger documents the manifest will be a problem to be loaded.

Check for a potential search server. (1h-2h)
