### ISSUE TITLE
Empty fields are not recognized as empty

### ISSUE THREAD

**Issue by ktk** [zazuko/amos#17]

**Comment by PlekszyGladz** [comment]
Null-values in `sources_scope.csv` are represented as empty cell, i.e. `,,`

**Comment by l00mi** [comment]
Seemed to be a typo in the IRI.

**Comment by l00mi** [comment]
Check also with instatation. e.g. https://data.ptt-archiv.ch/archive/record/209236

**Comment by PlekszyGladz** [comment]
Example of record with `rico:hasInstantiation` denoted by seperate AIP-identifier (this is how it should be): 
https://data.ptt-archiv.ch/archive/record/205575

Example of record that should not have any `rico:hasInstantiation` as there is no AIP-Identifier present in sources.csv:
https://data.ptt-archiv.ch/archive/record/205611

**Comment by ktk** [comment]
Ok the reason for that is:

```json
			{
				"propertyUrl": "https://www.ica.org/standards/RiC/ontology#hasInstantiation",
				"titles": "ID",
				"valueUrl": "https://data.ptt-archiv.ch/archive/record/{ID}/instantiation/{AIP-Referenz}"
			}
```

ID is never empty so it creates the IRI anyway. And according to the spec I would say that is correct behavior https://www.w3.org/TR/2015/REC-tabular-metadata-20151217/#uri-template-properties

**Comment by PlekszyGladz** [comment]
@ktk I see. Would the same be true, if we changed the url template for instantioation as follows:
`https://data.ptt-archiv.ch/archive/instantiation/{AIP-Referenz}`
so that there is no instantiation linked, when there is no `AIP-Referenz`?

If so, i can reflect these changes in the mapping.

**Comment by ktk** [comment]
@PlekszyGladz yes that would work, the other option is I add a filter to the pipeline that deletes those triples. It's quite easy to detect.

**Comment by PlekszyGladz** [comment]
I updated the URL-pattern as proposed, wich works well in the cases with an exisitng `AIP-Referenz`. All the other records are now linked with this single generic instantiation: https://data.ptt-archiv.ch/archive/instantiation/ 

The problem seems to be, that a few records have linked files but no AIP-Referenz. As we do not intend to do long term preservation of these files, this is intended.

So it seems we still need to filter for this (i.e. delete the genereic instantiation and all links to it). Alternatively we could remove the `AIP-Referenz` from the template altogether (something like this `https://data.ptt-archiv.ch/archive/record/{ID}/instantiation`) but this seems hacky, as there could be multiple instantiations for a single record according to RiC-O (wich, I guess, requires a uniqe identifier for instantiations in the uri).

**Comment by ktk** [comment]
Not sure I understand that, can you give an example IRI?

**Comment by PlekszyGladz** [comment]
Sorry got carried away thinking while writing...

Can you implement a Filter in the pieline:
- that removes this instantiation: `https://data.ptt-archiv.ch/archive/instantiation/`.  
- Also triples linking records with this instantiation need be removed (i.e. those matching this statement `?sub rico:hasInstantiation <https://data.ptt-archiv.ch/archive/instantiation/> .`)

**Comment by l00mi** [comment]
@ktk and @PlekszyGladz will have a meeting to solve this one.

**Comment by ktk** [comment]
Filter all triple where either subject or object IRI is `https://data.ptt-archiv.ch/archive/instantiation/`

**Comment by ktk** [comment]
I've added a new filter: https://gitlab.zazuko.com/amos/amos/-/blob/8020158d06e2375faa045bf7127650282364e196/lib/output-filter.js#L15-20
