### ISSUE TITLE
Order Process from the Interface

### ISSUE THREAD

**Issue by PlekszyGladz** [zazuko/amos#21]
List of Records are orderable by clicking the “In den analogen Lesesaal bestellen”-Button. 
Minimal additional Information that is required by the user to complete the order:
- Organisation
- Name*
- Address*
- Zip-Code* and Place*
- Country*
- Email*
- Telephone
- Preferred Date of loan*
- 
Clicking “senden” triggers an Email to archiv@mfk.ch containing the listed records and the above information.

- [ ] Fix the final list of export and email in the ptt-archive instance.

2h

**Comment by tpluscode** [comment]
@PlekszyGladz if you have any specific wording/structure in mind, please provide a template for what that email's contents could look like

What details about the records would you also have include in the email text? I assume it's more that just identifiers?

**Comment by PlekszyGladz** [comment]
@tpluscode the order email should look like the following:

> Sehr geehrte Damen und Herren
> Madame, Monsieur
> 
> 
> Gerne bestelle ich folgende Unterlagen zur Einsicht in den Lesesaal des PTT-Archivs.
> Je voudrais commander les documents suivants pour les consulter dans la salle de lecture des archives des PTT.
> 
> **Gewünschtes Datum und Zeit | Date et heure souhaitées**
> <table>
> <tr><td>Öffnungszeiten: Di, Mi, Fr, 09:00-17:00 Uhr<br>heures d'ouverture : mar, mer, ven, 09:00-17:00</td><td>Bitte ausfüllen/completez s'il vous plaît</td></tr>
> </table>
> 
> **Persönliche Angaben | Détails personnels**
> <table>
> <tr><td>Name<br>Nom</td><td>Bitte ausfüllen/completez s'il vous plaît</td></tr>
> <tr><td>Vorname<br>Prénom</td><td>Bitte ausfüllen/completez s'il vous plaît</td></tr>
> <tr><td>Adresse</td><td>Bitte ausfüllen/completez s'il vous plaît</td></tr>
> <tr><td>PLZ/Ort<br>Code postal/ville</td><td>Bitte ausfüllen/completez s'il vous plaît</td></tr>
> <tr><td>Tel.</td><td>Bitte ausfüllen/completez s'il vous plaît</td></tr>
> <tr><td>Email<br>Courriel</td><td>Bitte ausfüllen/completez s'il vous plaît</td></tr>
> </table>
> 
> **Bestellte Unterlagen | Documents commandés**
> 
> - \<Identifier>, \<Name>, \<Date Range>
> - \<Identifier>, \<Name>, \<Date Range>
> - \<Identifier>, \<Name>, \<Date Range>
> - \<Identifier>, \<Name>, \<Date Range>
>

**Comment by l00mi** [comment]
Add the html tag, and then we all test multiple clients.

**Comment by tpluscode** [comment]
Here's an example `mailto:` modified so that its contents are wrapped in `<html>`: [mailto link](mailto:archiv@mfk.ch?body=%3Chtml%3E%3Cbody%3E%3C%21----%3E%3C%21--%3Flit%24988927053%24--%3E%20%20%20%20%20%20%20%20%3Cstyle%3E%20%20%20%20%20%20%20%20%20%20%20%20table%20%7B%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20border-collapse%3A%20collapse%3B%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20border%3A%201px%20solid%20darkgrey%3B%20%20%20%20%20%20%20%20%20%20%20%20%7D%20%20%20%20%20%20%20%20%20%20%20%20td%20%7B%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20border%3A%201px%20solid%20darkgrey%3B%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20padding%3A%205px%3B%20%20%20%20%20%20%20%20%20%20%20%20%7D%20%20%20%20%20%20%20%20%20%20%20%20tr%3Anth-child%28even%29%20%7B%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20background-color%3A%20%23f5f5f5f5%3B%20%20%20%20%20%20%20%20%20%20%20%20%7D%20%20%20%20%20%20%20%20%3C%2Fstyle%3E%20%20%20%20%20%20%20%20%3Cp%3E%20%20%20%20%20%20%20%20%20%20%20%20Sehr%20geehrte%20Damen%20und%20Herren%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20Madame%2C%20Monsieur%20%20%20%20%20%20%20%20%3C%2Fp%3E%20%20%20%20%20%20%20%20%3Cp%3E%20%20%20%20%20%20%20%20%20%20%20%20Gerne%20bestelle%20ich%20folgende%20Unterlagen%20zur%20Einsicht%20in%20den%20Lesesaal%20des%20PTT-Archivs.%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20Je%20voudrais%20commander%20les%20documents%20suivants%20pour%20les%20consulter%20dans%20la%20salle%20de%20lecture%20des%20archives%20des%20PTT.%20%20%20%20%20%20%20%20%3C%2Fp%3E%20%20%20%20%20%20%20%20%3Cp%3E%3Cb%3EGew%C3%BCnschtes%20Datum%20und%20Zeit%20%7C%20Date%20et%20heure%20souhait%C3%A9es%3C%2Fb%3E%3C%2Fp%3E%20%20%20%20%20%20%20%20%3Ctable%3E%20%20%20%20%20%20%20%20%20%20%20%20%3Ctbody%3E%3Ctr%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Ctd%3E%C3%96ffnungszeiten%3A%20Di%2C%20Mi%2C%20Fr%2C%2009%3A00-17%3A00%20Uhr%3Cbr%3Eheures%20d%27ouverture%20%3A%20mar%2C%20mer%2C%20ven%2C%2009%3A00-17%3A00%3C%2Ftd%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Ctd%3EBitte%20ausf%C3%BCllen%2Fcompletez%20s%27il%20vous%20pla%C3%AEt%3C%2Ftd%3E%20%20%20%20%20%20%20%20%20%20%20%20%3C%2Ftr%3E%20%20%20%20%20%20%20%20%3C%2Ftbody%3E%3C%2Ftable%3E%20%20%20%20%20%20%20%20%3Cp%3E%3Cb%3EPers%C3%B6nliche%20Angaben%20%7C%20D%C3%A9tails%20personnels%3C%2Fb%3E%3C%2Fp%3E%20%20%20%20%20%20%20%20%3Ctable%3E%20%20%20%20%20%20%20%20%20%20%20%20%3Ctbody%3E%3Ctr%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Ctd%3EName%3Cbr%3ENom%3C%2Ftd%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Ctd%3EBitte%20ausf%C3%BCllen%2Fcompletez%20s%27il%20vous%20pla%C3%AEt%3C%2Ftd%3E%20%20%20%20%20%20%20%20%20%20%20%20%3C%2Ftr%3E%20%20%20%20%20%20%20%20%20%20%20%20%3Ctr%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Ctd%3EVorname%3Cbr%3EPr%C3%A9nom%3C%2Ftd%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Ctd%3EBitte%20ausf%C3%BCllen%2Fcompletez%20s%27il%20vous%20pla%C3%AEt%3C%2Ftd%3E%20%20%20%20%20%20%20%20%20%20%20%20%3C%2Ftr%3E%20%20%20%20%20%20%20%20%20%20%20%20%3Ctr%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Ctd%3EAdresse%3C%2Ftd%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Ctd%3EBitte%20ausf%C3%BCllen%2Fcompletez%20s%27il%20vous%20pla%C3%AEt%3C%2Ftd%3E%20%20%20%20%20%20%20%20%20%20%20%20%3C%2Ftr%3E%20%20%20%20%20%20%20%20%20%20%20%20%3Ctr%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Ctd%3EPLZ%2FOrt%3Cbr%3ECode%20postal%2Fville%3C%2Ftd%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Ctd%3EBitte%20ausf%C3%BCllen%2Fcompletez%20s%27il%20vous%20pla%C3%AEt%3C%2Ftd%3E%20%20%20%20%20%20%20%20%20%20%20%20%3C%2Ftr%3E%20%20%20%20%20%20%20%20%20%20%20%20%3Ctr%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Ctd%3ETel.%3C%2Ftd%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Ctd%3EBitte%20ausf%C3%BCllen%2Fcompletez%20s%27il%20vous%20pla%C3%AEt%3C%2Ftd%3E%20%20%20%20%20%20%20%20%20%20%20%20%3C%2Ftr%3E%20%20%20%20%20%20%20%20%20%20%20%20%3Ctr%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Ctd%3EEmail%3Cbr%3ECourriel%3C%2Ftd%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Ctd%3EBitte%20ausf%C3%BCllen%2Fcompletez%20s%27il%20vous%20pla%C3%AEt%3C%2Ftd%3E%20%20%20%20%20%20%20%20%20%20%20%20%3C%2Ftr%3E%20%20%20%20%20%20%20%20%3C%2Ftbody%3E%3C%2Ftable%3E%20%20%20%20%3C%21--%3Flit%24988927053%24--%3E%3Cul%3E%20%20%20%20%20%20%3C%21--%3Flit%24988927053%24--%3E%20%20%20%20%3C%2Ful%3E%3C%21--%3F--%3E&subject=Order%20records)

Do see if it makes any difference for your mail clients

**Comment by PlekszyGladz** [comment]
I tried Outlook and the Android Gmail-App and both displayed the html as plaintext. (Also i could not open the mailto link from Chrome, but that migth be a config problem on my side...)

Edit: I just found [this ](https://stackoverflow.com/questions/5620324/mailto-link-with-html-body) stack overwflow thread. It seems what we are trying here is not really supported. One solution might be [this answer](https://stackoverflow.com/a/46699855) but i consider this not really user friendly.

If there is really no way of using html as the mail body i suggest this simplified plaintext version:

> =====================================
> Vielen Dank für Ihre Anfrage. Bitte vervollständigen Sie mindestens die folgenden Angaben, damit wir Ihre Bestellung bearbeiten können.
> Merci pour votre demande. Veuillez compléter au moins les détails suivants afin que nous puissions traiter votre commande.
> \=====================================
> 
> Gewünschtes Datum und Zeit (Öffnungszeiten: Di, Mi, Fr, 09:00-17:00) |
> Date et heure souhaitées (heures d'ouverture : mar, mer, ven, 09:00-17:00): 
> 
> Name | Nom: 
> Vorname | Prénom: 
> Adresse: 
> PLZ/Ort | Code postal/ville: 
> Tel.: 
> Email | Courriel: 
> 
> 
> Bestellte Unterlagen | Documents commandés
> 
> \<Identifier>, \<Name>, \<Date Range>
> \<Identifier>, \<Name>, \<Date Range>
> \<Identifier>, \<Name>, \<Date Range>
> \<Identifier>, \<Name>, \<Date Range>

**Comment by tpluscode** [comment]
According to the comments the Chrome will by design block EML downloads and there are other special cases for various clients and browsers. Hardly a sustainable option

Unless we decide to go for an external mailer service plain text should be the way to go.

I'll keep code around to easily support both outputs and configure the app to send plain

**Comment by l00mi** [comment]
Change Subject to: Unterlagen Bestellen / Commander des documents

**Comment by PlekszyGladz** [comment]
![image](https://user-images.githubusercontent.com/5487333/139878873-057d0bf4-cf64-4f7a-b5f6-ac75f0913e56.png)

This is how the Link opens from Chrome to Outlook on my side

**Comment by PlekszyGladz** [comment]
The mail now opens correctly in all my browsers and mail clients.
Just e few small things before the issue can be closed:
1. Subject of the mail should be: "Unterlagen Bestellen / Commander des documents"
2. In the list of ordered documents at the bottom: display not only the links but the Identifier, Name and Date Range
3. Only Records of "Dossier" and "Document" Level can be ordered. All higher hierarchy entries should be removed. If this happens the user should be notified with the following message in a pop-up:

> In Ihrer Bestellliste befinden sich nicht bestellbare Einträge. Sie können nur Unterlagen der Stufe "Dossier" und "Dokument" in den Lesesaal bestellen. Einträge, die nicht bestellt werden können, wurden aus der Liste entfernt.
>
>Dans votre liste de commande, il y a des entrées qui ne peuvent pas être commandées. Vous ne pouvez commander que des documents de niveau "dossier" et "document" dans la salle de lecture. Les entrées qui ne peuvent pas être commandées ont été retirées de la liste.

**Comment by l00mi** [comment]
* First a pop-up appears with some text which @PlekszyGladz will provide.
* If some things need to be removed because non-orderable (not a Document/Dossier) it will show a warning.
* A button creates the email for the ordering.

**Comment by PlekszyGladz** [comment]
@tpluscode i wrote the new version of the pup-up info text notifying the users about the ordering process (including the removal of unorderable units)

>**Bestellung in den Lesesaal:** 
>Für eine Bestellung von Dokumenten in unseren Lesesaal ergänzen Sie bitte die folgende Email mit ihren persönlichen Angaben und dem Wunschdatum.
>
>Bitte beachten Sie, dass nur Unterlagen der Stufe "Dossier" und "Dokument" in den Lesessaal bestellt werden können. Einträge, die nicht bestellt werden können, werden aus der Liste entfernt.
>
>**Commande en salle de lecture:**
>Pour commander des documents dans notre salle de lecture, veuillez compléter l'e-mail suivant avec vos données personnelles et la date souhaitée.
>
>Veuillez noter que seuls les documents de niveau "dossier" et "document" peuvent être commandés dans la salle de lecture. Les entrées qui ne peuvent pas être commandées seront retirées de la liste.
> 
>**Folgende Unterlagen können nicht bestellt werden | Les documents suivants ne peuvent pas être commandés:**
>[List of removed entries]

**Comment by tpluscode** [comment]
I fixed the export and order. The defined properties are now shown again @PlekszyGladz
