### ISSUE TITLE
Display Description of Parent Hierarchy

### ISSUE THREAD

**Issue by PlekszyGladz** [zazuko/amos#29]
Does only apply to archival Data. When showing details of a records, also display [Form und Inhalt](https://www.ica.org/standards/RiC/RiC-O_v0-2.html#scopeAndContent) from parent hierarchy, as the description of the lowest hierarchy can be to specific

**Comment by l00mi** [comment]
* Expand the hierarchy band to double side and show the Identifiers (Signatur).
* Show the ScopeAndContent as Tooltip if hovered over the hierarchy item.

**Comment by tpluscode** [comment]
@PlekszyGladz please have a look at the first proposal for this. Hovering over the hierarchy will, after a short delay, show the identifier + scope and content over the rest of the record.

@l00mi proposed to show only the identifier and a tooltip for scope & content but it is a potentially a long text so I went for an ellipsis and a link to the details page.

Since this had to be implemented only to archive records and I had to differentiate the rendering, I added a temporary fix for #60, showing a blue button for library entries. Imperfect but we'll improve later

**Comment by l00mi** [comment]
Minor changes:
Show the ricoIdentifier below each hierarchy step, only the one selected "clickable" and other color.
Keep the scopeAndContent on the second line.

**Comment by tpluscode** [comment]
@l00mi I applied changes as discussed last week. Notice a slight deviation from your comment above. When the hierarchy slides down, all levels are always clickable. This way one does not have to go back and point on the colored segments above.

It appears that some levels do not have their `scopeAndContent` which results in a blank line when hovered. Maybe it's fine or maybe we would add some fallback text?

**Comment by l00mi** [comment]
@tpluscode overall I think it is good like is. The only expectation I would have to have the codes vertically aligned with the hierarchy above. We might for that stretch actually the hierarchy bar itself?

**Comment by PlekszyGladz** [comment]
I agree with @l00mi. In addition there should be some indication of the active scopeAndContent that is currently displayed. Maybe by only underlining only the hoverd identifier-links?

**Comment by tpluscode** [comment]
I changed how the hovered level is highlighted (underline and bold)

Aligning them vertically will not be that easy because they are actually rendered separately and also potentially not matching width. In a rare occasion the code is longer than the label
