### ISSUE TITLE
Provide images on IIIF Server

### ISSUE THREAD

**Issue by ktk** [zazuko/amos#42]
- [x] @ludovicm67 creates the final DO buckets and shares the API Key to @PlekszyGladz to provide all the images.
- [x] @PlekszyGladz provides the pictures.

4h

**Comment by l00mi** [comment]
@ktk what are the next steps here?

**Comment by l00mi** [comment]
@ludovicm67 we need to quickly discuss on this how to proceed. can you make a meeting with us.

**Comment by ludovicm67** [comment]
Yes, we can have a meeting for that. Can you schedule one meeting?

**Comment by ktk** [comment]
@PlekszyGladz could you comment again about the size & amount of images so we can do some calculations?

**Comment by ludovicm67** [comment]
Some S3 providers:

- [DigitalOcean Spaces](https://docs.digitalocean.com/products/spaces/)
- [Amazon S3](https://aws.amazon.com/s3/pricing/)
- [CloudFlare R2](https://blog.cloudflare.com/introducing-r2-object-storage/) (⚠️ not available yet)

Some other alternatives: https://www.coralnodes.com/amazon-s3-alternatives/

**Comment by l00mi** [comment]
@ludovicm67 where is the more indepth analysis you did? What is the takeaway again?

**Comment by l00mi** [comment]
@PlekszyGladz can you please make the CNAME DNS entry for `iiif.ptt-archiv.ch` to `iiif-ptt-archiv-ch.zazuko.net`

**Comment by PlekszyGladz** [comment]
>can you please make the CNAME DNS entry for iiif.ptt-archiv.ch to iiif-ptt-archiv-ch.zazuko.net

@l00mi should work now

**Comment by l00mi** [comment]
* We need to understand why its slow?
* If it can be remedied in S3 of DO?
  * if yes move data to DO
  * if no find other storage solution.

**Comment by l00mi** [comment]
Is it okay to convert everything to jpeg2000? @PlekszyGladz we will discuss this in the next review.

**Comment by ludovicm67** [comment]
For IIIF images, I really want to use JPG2000 images instead of TIF, to solve performances issues and to avoid strange issues with multi-pages documents like I saw when using TIF (when zooming on a multipage document, it was showing tiles from random pages, I will not be able to fix this ; but using JPG2000 is solving this issue).
I also removed cache expiration, so only the first time we load an image or a tile will take a few seconds, but it's not really an issue, performances are still fine. But if the cache is becoming too big, I will add expiration back again.

If you don't want to care about the TIF→JPG2000 conversion, I can create a cron job that will automatically convert all TIF files to JPG2000.

**Some questions:**
- At what frequency do AMOS plan to update images? Is it OK if I run a dedicated cronjob for the conversion only once a day?
- Should I keep original TIF files? For information, this will require some more storage.

**Note:**
It's always possible to get the full size version of an image and have it in multiple formats (just change the final extension, as shown in the following examples):
  - JPG: https://iiif.ptt-archiv.ch/iiif/3/Telefonb%C3%BCcher%2FP-260-1_Basel_1884%2FP-260-1_Basel_1884_0001.jp2/full/max/0/default.jpg
  - TIF: https://iiif.ptt-archiv.ch/iiif/3/Telefonb%C3%BCcher%2FP-260-1_Basel_1884%2FP-260-1_Basel_1884_0001.jp2/full/max/0/default.tif
  - PNG: https://iiif.ptt-archiv.ch/iiif/3/Telefonb%C3%BCcher%2FP-260-1_Basel_1884%2FP-260-1_Basel_1884_0001.jp2/full/max/0/default.png

@PlekszyGladz what are your thoughts about this?

**Comment by PlekszyGladz** [comment]
> If you don't want to care about the TIF→JPG2000 conversion, I can create a cron job that will automatically convert all TIF files to JPG2000.

that would be great

> Some questions:
> At what frequency do AMOS plan to update images? Is it OK if I run a dedicated cronjob for the conversion only once a day?

Updating well be sporadically and dependant on our scanning projects. So once a day will be enough!

> Should I keep original TIF files? For information, this will require some more storage.

As we keep the TIFs for internal use anyways, I don't see any need to keep them on the S3 Server

**Comment by ludovicm67** [comment]
I created the cronjob. It's based on this: https://github.com/zazuko/s3-image-converter
The cronjob is running every hour, when minutes equals to 5, so that we don't have to wait an eternity to see if conversions are working well. I will/can change the frequency depending on our needs.
It is configured to convert all TIF files present in the S3 bucket to JP2 one.
TIF files are removed after conversion.

@PlekszyGladz I sent you S3 credentials in private message on Zulip.

Can you try to upload some TIF files in the bucket so that we can see if conversion is working as expected?

**Comment by ludovicm67** [comment]
For information, I changed the cronjob frequency to be run only once a day, at 04:05 UTC.
