### ISSUE TITLE
Add a skos:hiddenField to represent everything to search on.

### ISSUE THREAD

**Issue by l00mi** [zazuko/amos#43]
Queries should not only search Titles (at least also rico.scopeAndContent)

This will be used as the index for searching.

Create a INSERT SPARQL query which will be run after the upload to create.

Hidden fields to insert:
- [x] Searching: `rico:name` (full upper hierarchy) + `rico:scopeAndContent` (only current record) + `rico:identifier` (only current record) + `rico:descriptiveNote` (only current record)
- [x] Sorting by name (as dscribed at #50): `rico:name` without any leading non-alphanumerical characters
- [x] Sorting by hierarchy (as dscribed at #50): `rico:identifier` (full upper hierarchy)

**Comment by l00mi** [comment]
include all:
* title (full upper hierarchy)
* scopeAndContent (only document)
* ricoIdentifier (only document)

Edit by @PlekszyGladz: also include rico.descriptiveNote (only document)

**Comment by l00mi** [comment]
@ktk makes a first manual insertion.

**Comment by PlekszyGladz** [comment]
@ktk and @tpluscode I added specs for all currently required hidden fields in the [first ](https://github.com/zazuko/amos/issues/43#issue-1022723213) comment of this thread

**Comment by tpluscode** [comment]
Here's my best attempt at the query to build the hierarchy ordering string: https://s.zazuko.com/Pjb1X

**Comment by tpluscode** [comment]
I propose this query to replace all leading non-alphanumeric characters: https://s.zazuko.com/fcdZvP

Notice the artificial predicate `https://data.ptt-archiv.ch/sort-by#title`. I have no better idea for annotating the records other than with a targeted property specific to our data. `skos:hiddenLabel` doesn't work for sorting if we'd intend to use it for more than just titles

**Comment by tpluscode** [comment]
Finally, regarding search, I propose we simply change the `fulltext-part` to match ont only the titles but also the other properties as listed in the first bullet.

For that purpose I would introduce a new predicate for the concatenated hierarchy, similarly to the the "sort by title" above. Here's a revise query which CONSTRUCTs what would be inserted: https://s.zazuko.com/5rjPqJ

Thus, the full text patterns would be extended as follows, to search between all required values

```diff
{ ?sub <https://www.ica.org/standards/RiC/ontology#name> ?l .}
UNION
{ ?sub <http://rdaregistry.info/Elements/m/workManifested>/<http://rdaregistry.info/Elements/w/titleOfTheWork> ?l.}
+UNION
+{ ?sub <https://data.ptt-archiv.ch/archive/record#hierarchy> ?l }
+UNION
+{ ?sub rico:scopeAndContent ?l }
+UNION
+{ ?sub rico:descriptiveNote ?l }

(?l ?score) <tag:stardog:api:property:textMatch> "${searchString}" .
```

**Comment by tpluscode** [comment]
To sum up after a call with @ktk 

**Sorting by hierarchy**

We will use `skos:notation`, to store the full, concatenated hierarchy (identifiers) to use for sorting. It will also include the identifier of the item in question

@PlekszyGladz, do we still have missing hierarchy levels for some items? This will prevent us from building the complete "hierarchy string". If so, could you provide an example? The pipeline will have to substitute the missing levels with a "blank"

**Improved full-text search**

We will indeed use the `skos:hiddenField` as initially proposed. It contents will be a merger of all parents' `rico:name` so that we can reference it efficiently in queries. 

To actually get a final score for any record, the `?score` will be aggregated to combine the partial scores of various matching properties. Might go for `sum` or even `avg` so that archive data is not prioritised over library entries.

---

Here is the final query which we can use to populate the data with `skos:notation` and `skos:hierarchy`: https://s.zazuko.com/xdyen

**Comment by PlekszyGladz** [comment]
also search rico:identifier
