### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by l00mi** [zazuko/amos#50]
Introduce a sorting of records:

* by Score
* by Time
* by Hierarchy
* by Type > from lowest in hiearachy to highest

**Comment by l00mi** [comment]
![Screenshot 2021-12-02 at 11 50 02](https://user-images.githubusercontent.com/502518/144408568-4675358b-160e-471a-8f07-fb60a8f45a1f.png)

**Comment by l00mi** [comment]
For the sorting we could take over the same element of https://www.mfk.ch/austauschen/blog
<img width="1964" alt="Screenshot 2021-12-22 at 12 07 25" src="https://user-images.githubusercontent.com/502518/147083589-6c2e3694-9064-478b-9c32-3440dae92cd4.png">

It would be below the Timeline.

**Comment by tpluscode** [comment]
Sorting is up, byt title and date. I used the fonts from mfk.ch but not the full styling as it underlines on hover...

@PlekszyGladz

**Comment by PlekszyGladz** [comment]
Looks good and works as intended!
Some thoughts though on how to further improve the sorting:

* [x] Switch position of sorting and active filter, so that the sorting is always directly on top of the search results.
* [x] Sorting by name: as you predicted there are many titles starting with special characters such as quotes, wich show on top of the list. For sorting purposes only alpha-numeric characters should be evaluated --> do we need a hidden field for that, or can we do this in the query without a huge performance drop?
* [x] I kind of miss the default sorting by "score" we used to have, especially when searching with multiple terms. E.g. searching "Poststellenchronik Aarberg" is not showing the desired [record](https://data.ptt-archiv.ch/archive/record/205575)  on top.
* [x] Still open is sorting by hierarchy and/or by identifier. For now we should implement the latter, as this should be quite easy. The hierarchy sorting could maybe be done via a hidden field containing all the concatenated identifiers of the hierarchy (The Aarberg example would look somethinh like this: "CH-PTT-Archiv DOK DK CHR OT Post-199 A 0003 Post-199 A 0003_Aarberg").

**Comment by tpluscode** [comment]
@PlekszyGladz I moved the sorting as requested and also added a "best match" sorting. I only shows when full text search is used and gets selected, replacing any current sorting. Of course it can always be changed and it also reverts to previous selection when text field is cleared

Regarding the other two point, we'd need to make changes to the pipeline so that we pre-compute the necessary values. Running such filters in the query on the fly would be very taxing, if at all possible

**Comment by PlekszyGladz** [comment]
Implement hidden fields at #43

**Comment by tpluscode** [comment]
Technically the hierarchy sorting is up but any record without parents (such as all of library but also some archive records) will appear on top. That is probably not the desired effect

@PlekszyGladz we have two options:

1. Implicitly filter out results without a hierarchy when sorting. In other words only show those that do.
2. Sort so that anything with missing hierarchy string will be at the end of all results

**Comment by PlekszyGladz** [comment]
@tpluscode thx for the update

I think the second option is better. (Especially for queries that yield only a small number of results containing some library records)

**Comment by PlekszyGladz** [comment]
sorting by hierarchy is still not properly working as seen in this example:
![image](https://user-images.githubusercontent.com/5487333/174022773-74ee46b9-ddd4-4fdc-8632-58b097c8588f.png)
The three marked records from "Sammlungen und Nachlässe" should be grouped together and ordered the other way around

**Comment by tpluscode** [comment]
Please see now @PlekszyGladz. Every page of results should have proper display order
