### ISSUE TITLE
Missing hierarchies

### ISSUE THREAD

**Issue by tpluscode** [zazuko/amos#52]
I noticed today that there are broken hierarchy links from some records

For example, see https://data.ptt-archiv.ch/search/?q=pakete

Nothing shows for `Nachfragen Pakete mit und ohne Wertangabe Ausland` and some others. This one in particular is https://data.ptt-archiv.ch/archive/record/33718 and indeed the `rico:isOrWasIncludedIn` links to https://data.ptt-archiv.ch/archive/record/222 which does not exist

**Comment by PlekszyGladz** [comment]
The reason is the source data of some records in scopeArchiv. It is possible to mark a record as public (i.e. at least the metadata of the record) but protect the parent entry. 

This can happen due to legal times of protection or the fact that the archival description of the parent is still ongoing while the child has been completed.

We should try internally to clean these up sometimes, but this is nothing we can do quickly. So the broken links will most likely remain for the moment. The Problem is also exisitng in our current online database (see the marked protected Entries) 
![image](https://user-images.githubusercontent.com/5487333/141081154-a9db0062-44da-4707-9513-9d4011799ee9.png)

@tpluscode is it functionally necessary to fix these broken links? if so, I would try to export these entries as dummies titled "geschützter Eintrag" with just the id and the parent id.
