### ISSUE TITLE
First Tests with Video Manifest

### ISSUE THREAD

**Issue by l00mi** [zazuko/amos#62]
https://iiif.io/api/cookbook/recipe/0003-mvm-video/

**Comment by ludovicm67** [comment]
I've done some tests using the IIIF server to see the answers we can have.

Using: https://iiif.ptt-archiv.ch/iiif/3/Oral-History%2F012-SAM-OHP_037%2F012-SAM-OHP_037_Interview.mov/info.json

Gives the following output:

```json
{
  "@context":"http://iiif.io/api/image/3/context.json",
  "id":"https://iiif.ptt-archiv.ch/iiif/3/Oral-History%2F012-SAM-OHP_037%2F012-SAM-OHP_037_Interview.mov",
  "type":"ImageService3",
  "protocol":"http://iiif.io/api/image",
  "profile":"level2",
  "width":1920,
  "height":1080,
  "maxArea":2073600,
  "sizes":[
    {
      "width":120,
      "height":68
    },
    {
      "width":240,
      "height":135
    },
    {
      "width":480,
      "height":270
    },
    {
      "width":960,
      "height":540
    },
    {
      "width":1920,
      "height":1080
    }
  ],
  "tiles":[
    {
      "width":512,
      "height":512,
      "scaleFactors":[
        1,
        2,
        4,
        8,
        16
      ]
    }
  ],
  "extraQualities":[
    "bitonal",
    "color",
    "gray"
  ],
  "extraFormats":[
    "tif",
    "gif"
  ],
  "extraFeatures":[
    "baseUriRedirect",
    "canonicalLinkHeader",
    "cors",
    "jsonldMediaType",
    "mirroring",
    "profileLinkHeader",
    "regionByPct",
    "regionByPx",
    "regionSquare",
    "rotationArbitrary",
    "rotationBy90s",
    "sizeByConfinedWh",
    "sizeByH",
    "sizeByPct",
    "sizeByW",
    "sizeByWh"
  ]
}
```

Using the IIIF server can be useful if we need to be able to generate thumbnails at every moment on this specific video. Is it something we would need or not? For information, it will not be used in the manifest file.

So we do not need the IIIF server to generate the manifest file for videos.
What I can do is to create a dedicated S3 bucket where videos can be stored and served.

I will also need to create a little service that will be connected to this S3 bucket that can extract some details about the video:
- width and height
- duration (this information is not returned by the IIIF server)

We will be able to serve videos directly from the S3 bucket.
If we require some access control in the future, we can use tokens to access resources from the S3 bucket so that they are not publicly available. It's something that is already supported by S3, but will require adapting the service that is generating the manifests file to generate a dedicated token and provide it in the manifest.

For my point of view, we don't need the IIIF server for generating manifests for videos.
We can manage the videos separately and simply create a little service to fetch the required details about a specific video. If we really need a thumbnail at some point, we can use this service to generate one using the first frame of the video.

**Comment by ludovicm67** [comment]
How I see the thing:
- someone upload videos on the dedicated S3 bucket
- a cronjob is run once a day to get the duration, width and height of each video and set this as S3 metadata on each file
- The AMOS pipeline will call a service that I will need to write, that basically just returns the S3 metadata of the requested video ; if metadata are not existing, if will need to wait the next run of the pipeline
- at this point, all required metadata would be available in the triplestore ; the manifests service can fetch them and generate a manifest for each video

**Comment by ludovicm67** [comment]
After improving the pipeline to add support for videos, I did some tests for generating manifests. It seems that the duration is not required for displaying it in the IIIF viewer.

In the current state, the pipeline is querying the IIIF-server (first call is slow, then the next one are instant) to get the with, height and the thumbnail.
Videos are exposed publicly, but I will need to create a service to fetch videos from the S3 bucket. This will be required if we want to add some kind of access control.

Other point: the MOV file format is badly supported. We should use the MP4 version of the videos if possible.

**Comment by PlekszyGladz** [comment]
@ludovicm67 I provided two MP4 examples on the s3 bucket

**Comment by ludovicm67** [comment]
Thank you @PlekszyGladz for providing the videos!

Here is an example of a generated video manifest: https://data.ptt-archiv.ch/archive/instantiation/CH-000525-4%3Aaip-01-0000202776-0001/manifest

And here how it looks like in the web interface: https://data.ptt-archiv.ch/archive/record/202776
