### ISSUE TITLE
title of parent record is missing on detail page

### ISSUE THREAD

**Issue by PlekszyGladz** [zazuko/amos#80]
![image](https://user-images.githubusercontent.com/5487333/167629257-eaf24f19-d8e2-4bcd-9ad8-874595144ea2.png)

**Comment by tpluscode** [comment]
Have we changed how the data is prepared @ktk? Or maybe this never displayed correctly @PlekszyGladz 

Until now the template assumed that the `rico:name` of record sets was an `rdf:langString`. Currently, because no tagged literals are found, nothing is displayed. 

I can fall back to plain literal in such case but maybe tagged literal should not be expected at all?

**Comment by PlekszyGladz** [comment]
I'm quite sure, that it displayed initially - but i might also be wrong ;) The `rico:name` has no language tag, because we have some french titles in our records

@tpluscode at the moment, nothing is displayed at all. The detail page just shows the blank template. Can you check what is broken?

**Comment by tpluscode** [comment]
Sorry about that. Deploying now

**Comment by PlekszyGladz** [comment]
perfect! seems to work now
