### ISSUE TITLE
Fix broken IIIF manifests

### ISSUE THREAD

**Issue by ludovicm67** [zazuko/amos#89]
We have a Trifid plugin who is in charge of building the right IIIF manifest.
But we currently have some issue: they look broken.

When I investigated last time, the issue was coming from the way the triplestore was handling the blank nodes.
`CLEAR` the graph, triggering the pipeline again and clearing the cache was solving the issue last time.

Maybe using `PUT` instead of `POST` when writing in the graphs may solve this issue?

**Comment by ktk** [comment]
That's probably because bnode IDs are preserved right now on the amos DB, so we create clashes if we re-use IDs. This can be fixed by taking the DB offline, change the `preserve.bnode.id` setting to off & re-write the data (after a clear).

See https://docs.stardog.com/operating-stardog/database-administration/database-configuration#preservebnodeids

**Comment by ludovicm67** [comment]
The setting is already `off`, so this is not the issue.
Maybe the fault of some old data?
I will clear everything in that database and deploy everything back there by running the `deploy` step from the pipeline.

**Comment by ludovicm67** [comment]
It's now able to generate working manifests again.
